load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["zenoss.go"],
    importpath = "github.com/neticdk/go-zenoss/zenoss",
    visibility = ["//visibility:public"],
)
