name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Mount bazel cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Run tests
        run: bazel test //...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        env:
          # https://github.com/securego/gosec/issues/776
          GOROOT: ""
        with:
          args: ./...

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "library"
